 pipeline {
    agent any // Any available agent can run this pipeline

    // environment {
    //     CI = 'true'
    //     scannerHome = '/opt/sonar-scanner'
    // }

    // stages {
    //     stage('SonarQube analysis') {
    //         agent {
    //             docker {
    //                 image 'amd64/sonarqube'
    //             }
    //         }
    //         steps {
    //             withSonarQubeEnv('Sonar') {
    //                 sh "${scannerHome}/bin/sonar-scanner"
    //             }
    //         }
    //     }
        
        stage('build') {
            steps {
                echo 'Build stage: Hello World'
                // Add your build commands here
            }
        }

        stage('deploy') {
            steps {
                echo 'Deploy stage: run successfully'
                // Add your deployment commands here
            }
        }
    }
}

