pipeline { //# parent - contians the pipeline hi
    agent any //# any node can run the job. it can be specified too 

    stages {
        stage('build') { //# must have a unique name 
            steps { // # commands run inside a step 
                echo 'Hello World'
            }
        }


        stage('test') { //# must have a unique name 
            steps { // # commands run inside a step 
                echo 'Hello World'
            }
        }



        stage('deploy') { //# must have a unique name 
            steps { // # commands run inside a step 
                echo 'Hello World'
            }
        }



        
    }
}
